packages:
  - "apps/*"
  - "libs/*"
ignoreWorkspaceRootCheck: true
allowBuilds:
  nx: true
  unrs-resolver: true
  "@swc/core": false
  "@nestjs/core": false
  '@parcel/watcher': true
  less: true
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true
  sharp: true
onlyBuiltDependencies:
  - unrs-resolver
  - "@swc/core"
  - esbuild
  - nx
